#!/bin/bash

set -ex

export NODE_OPTIONS=--openssl-legacy-provider

# differentiate github icons
jupyter serverextension disable --py jupyter_offlinenotebook --sys-prefix
jupyter nbextension disable --py jupyter_offlinenotebook --sys-prefix

# TODO build args seem to be necessary in low memory environment w/ jlab 2.x
jupyter lab build --dev-build=False --minimize=False
jupyter lab workspaces import binder/workspace.json
